
import { Vehicle } from '@/types/vehicle';

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'v1',
    title: 'Yamaha MT-15 V2',
    brand: 'Yamaha',
    model: 'MT-15',
    type: 'bike',
    year: 2022,
    km_run: 8500,
    price: 415000,
    description: 'Excellent condition MT-15 V2 with all original accessories. Well maintained and single owner used.',
    image_urls: ['https://picsum.photos/seed/mt15/600/400'],
    condition: 'Excellent',
    status: 'available',
    created_at: new Date().toISOString(),
    featured: true
  },
  {
    id: 'v2',
    title: 'Honda Dio BS6',
    brand: 'Honda',
    model: 'Dio',
    type: 'scooter',
    year: 2021,
    km_run: 12000,
    price: 185000,
    description: 'Very neat and clean Dio BS6. Great mileage and smoothness.',
    image_urls: ['https://picsum.photos/seed/dio/600/400'],
    condition: 'Good',
    status: 'available',
    created_at: new Date().toISOString(),
    featured: true
  },
  {
    id: 'v3',
    title: 'Royal Enfield Classic 350',
    brand: 'Royal Enfield',
    model: 'Classic 350',
    type: 'bike',
    year: 2020,
    km_run: 15000,
    price: 450000,
    description: 'Black gold color RE Classic. Perfect engine health and iconic thump.',
    image_urls: ['https://picsum.photos/seed/classic350/600/400'],
    condition: 'Excellent',
    status: 'available',
    created_at: new Date().toISOString(),
    featured: false
  },
  {
    id: 'v4',
    title: 'Suzuki Burgman Street',
    brand: 'Suzuki',
    model: 'Burgman',
    type: 'scooter',
    year: 2023,
    km_run: 4000,
    price: 265000,
    description: 'Almost brand new Burgman Street. High utility and comfort.',
    image_urls: ['https://picsum.photos/seed/burgman/600/400'],
    condition: 'Like New',
    status: 'available',
    created_at: new Date().toISOString(),
    featured: false
  },
  {
    id: 'v5',
    title: 'Bajaj Pulsar NS 200',
    brand: 'Bajaj',
    model: 'NS 200',
    type: 'bike',
    year: 2019,
    km_run: 22000,
    price: 245000,
    description: 'Powerful performance and stylish looks. NS 200 in fair condition.',
    image_urls: ['https://picsum.photos/seed/ns200/600/400'],
    condition: 'Fair',
    status: 'sold',
    created_at: new Date().toISOString(),
    featured: false
  },
  {
    id: 'v6',
    title: 'TVS Ntorq 125 XP',
    brand: 'TVS',
    model: 'Ntorq',
    type: 'scooter',
    year: 2022,
    km_run: 9000,
    price: 210000,
    description: 'High performance scooter with smart connectivity features.',
    image_urls: ['https://picsum.photos/seed/ntorq/600/400'],
    condition: 'Excellent',
    status: 'available',
    created_at: new Date().toISOString(),
    featured: false
  }
];
